#ifndef __OPENRAVE_YARP_PLANNER_LOG_COMPONENT_HPP__
#define __OPENRAVE_YARP_PLANNER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ORYP)

#endif // __OPENRAVE_YARP_PLANNER_LOG_COMPONENT_HPP__
