#ifndef __YARP_OPENRAVE_GRABBER_LOG_COMPONENT_HPP__
#define __YARP_OPENRAVE_GRABBER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YORG)

#endif // __YARP_OPENRAVE_GRABBER_LOG_COMPONENT_HPP__
