#ifndef __YARP_OPENRAVE_RGBDSENSOR_LOG_COMPONENT_HPP__
#define __YARP_OPENRAVE_RGBDSENSOR_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YORRS)

#endif // __YARP_OPENRAVE_RGBDSENSOR_LOG_COMPONENT_HPP__
