#ifndef __YARP_OPENRAVE_CONTROLBOARD_LOG_COMPONENT_HPP__
#define __YARP_OPENRAVE_CONTROLBOARD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YORCB)

#endif // __YARP_OPENRAVE_CONTROLBOARD_LOG_COMPONENT_HPP__
