#ifndef __OPENRAVE_YARP_WORLD_LOG_COMPONENT_HPP__
#define __OPENRAVE_YARP_WORLD_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ORYW)

#endif // __OPENRAVE_YARP_WORLD_LOG_COMPONENT_HPP__
