#ifndef __YARP_OPENRAVE_ROBOT_MANAGER_LOG_COMPONENT_HPP__
#define __YARP_OPENRAVE_ROBOT_MANAGER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YORRM)

#endif // __YARP_OPENRAVE_ROBOT_MANAGER_LOG_COMPONENT_HPP__
