#ifndef __YARP_OPENRAVE_SIMULATION_LOG_COMPONENT_HPP__
#define __YARP_OPENRAVE_SIMULATION_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(YORS)

#endif // __YARP_OPENRAVE_SIMULATION_LOG_COMPONENT_HPP__
