#ifndef __OPENRAVE_YARP_PLUGIN_LOADER_LOG_COMPONENT_HPP__
#define __OPENRAVE_YARP_PLUGIN_LOADER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ORYPL)

#endif // __OPENRAVE_YARP_PLUGIN_LOADER_LOG_COMPONENT_HPP__
