name: Continuous Integration

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'
  pull_request:
  schedule:
  - cron: '0 0 * * FRI'
  workflow_dispatch:

env:
  CMAKE_CCACHE_LAUNCHER: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{steps.skip_check.outputs.should_skip}}
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      id: skip_check
      with:
        cancel_others: 'true'

  build:
    name: build (${{matrix.os}}, ${{matrix.robotology.yarp}}, ${{matrix.compiler.cc}})
    runs-on: ${{matrix.os}}
    needs: maybe_skip
    if: ${{needs.maybe_skip.outputs.should_skip != 'true'}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        robotology:
        - { yarp: yarp-3.7, cmake: 3.16.x }
        - { yarp: yarp-3.8, cmake: 3.16.x }
        - { yarp: master, cmake: 3.16.x }
        compiler:
        - { cc: gcc, cxx: g++ }
        - { cc: clang, cxx: clang++ }
        experimental:
        - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
        exclude:
        - { experimental: false, robotology: { yarp: master } }

    steps:
    - name: Check out openrave-yarp-plugins
      uses: actions/checkout@v3

    - name: Check out YCM
      uses: actions/checkout@v3
      with:
        repository: robotology/ycm
        path: .deps/ycm

    - name: Check out YARP
      uses: actions/checkout@v3
      with:
        repository: robotology/yarp
        ref: ${{matrix.robotology.yarp}}
        path: .deps/yarp

    - name: Check out RapidJSON
      uses: actions/checkout@v3
      with:
        repository: Tencent/rapidjson
        path: .deps/rapidjson

    - name: Check out OpenRAVE
      uses: actions/checkout@v3
      with:
        repository: rdiankov/openrave
        path: .deps/openrave

    - name: Check out asrob-uc3m/yarp-devices
      uses: actions/checkout@v3
      with:
        repository: asrob-uc3m/yarp-devices
        path: .deps/yarp-devices

    - name: Check out roboticslab-uc3m/vision
      uses: actions/checkout@v3
      with:
        repository: roboticslab-uc3m/vision
        path: .deps/vision

    - name: Check out roboticslab-uc3m/kinematics-dynamics
      uses: actions/checkout@v3
      with:
        repository: roboticslab-uc3m/kinematics-dynamics
        path: .deps/kinematics-dynamics

    - name: Install dependencies via apt
      run: sudo apt-get update && sudo apt-get install -qq ccache libboost-regex-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libxml2-dev libpcl-dev

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{matrix.robotology.cmake}}

    - name: Set up Ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{matrix.os}}-${{matrix.robotology.yarp}}-${{matrix.compiler.cc}}

    - name: Set environment variables
      run: |
        echo "CC=${{matrix.compiler.cc}}" >> $GITHUB_ENV
        echo "CXX=${{matrix.compiler.cxx}}" >> $GITHUB_ENV

    - name: Build YCM
      run: |
        cmake -S .deps/ycm -B .deps/ycm/build
        cmake --build .deps/ycm/build
        sudo cmake --install .deps/ycm/build

    - name: Build YARP
      run: |
        cmake -S .deps/yarp -B .deps/yarp/build $CMAKE_CCACHE_LAUNCHER -DSKIP_ACE=ON -DYARP_DISABLE_VERSION_SOURCE=ON
        cmake --build .deps/yarp/build
        sudo cmake --install .deps/yarp/build

    - name: Build RapidJSON
      run: |
        cmake -S .deps/rapidjson -B .deps/rapidjson/build $CMAKE_CCACHE_LAUNCHER -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF -DRAPIDJSON_BUILD_TESTS=OFF
        cmake --build .deps/rapidjson/build
        sudo cmake --install .deps/rapidjson/build

    - name: Build OpenRAVE
      run: |
        CFLAGS=-w CXXFLAGS=-w cmake -S .deps/openrave -B .deps/openrave/build $CMAKE_CCACHE_LAUNCHER -DOPT_VIDEORECORDING=OFF -DOPT_PLUGINS=OFF -DOPT_PYTHON=OFF -DOPT_COLLADA=OFF -DOPT_CBINDINGS=OFF
        cmake --build .deps/openrave/build
        sudo cmake --install .deps/openrave/build

    - name: Build asrob-uc3m/yarp-devices
      run: |
        cmake -S .deps/yarp-devices -B .deps/yarp-devices/build $CMAKE_CCACHE_LAUNCHER
        cmake --build .deps/yarp-devices/build
        sudo cmake --install .deps/yarp-devices/build

    - name: Build roboticslab-uc3m/vision
      run: |
        cmake -S .deps/vision -B .deps/vision/build $CMAKE_CCACHE_LAUNCHER -DDOWNLOAD_MODELS=OFF
        cmake --build .deps/vision/build
        sudo cmake --install .deps/vision/build

    - name: Build roboticslab-uc3m/kinematics-dynamics
      run: |
        cmake -S .deps/kinematics-dynamics -B .deps/kinematics-dynamics/build $CMAKE_CCACHE_LAUNCHER
        cmake --build .deps/kinematics-dynamics/build
        sudo cmake --install .deps/kinematics-dynamics/build

    - name: Configure openrave-yarp-plugins
      run: cmake -S . -B build $CMAKE_CCACHE_LAUNCHER -DENABLE_examples=ON

    - name: Compile openrave-yarp-plugins
      run: cmake --build build

    - name: Install openrave-yarp-plugins
      run: sudo cmake --install build && sudo ldconfig

    - name: Uninstall openrave-yarp-plugins
      run: sudo cmake --build build --target uninstall
