name: Continuous Integration

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'
  pull_request:
  schedule:
  - cron: '0 0 * * FRI'
  workflow_dispatch:

env:
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{steps.skip_check.outputs.should_skip}}
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      id: skip_check
      with:
        cancel_others: 'true'

  build:
    name: build (${{matrix.system.os}}, ${{matrix.robotology.yarp}}, ${{matrix.system.compiler.cc}})
    runs-on: ${{matrix.system.os}}
    needs: maybe_skip
    if: ${{needs.maybe_skip.outputs.should_skip != 'true'}}

    strategy:
      fail-fast: false
      matrix:
        system:
        - { os: ubuntu-22.04, compiler: { cc: gcc-11,   cxx: g++-11 } }
        # https://github.com/roboticslab-uc3m/questions-and-answers/issues/101
        - { os: ubuntu-22.04, compiler: { cc: clang-15, cxx: clang++-15 } }
        - { os: ubuntu-24.04, compiler: { cc: gcc-13,   cxx: g++-13 } }
        - { os: ubuntu-24.04, compiler: { cc: clang-18, cxx: clang++-18 } }
        robotology:
        - { yarp: yarp-3.11, cmake: 3.19.x }
        - { yarp: yarp-3.12, cmake: 3.19.x }
        - { yarp: master,    cmake: 3.19.x }
        experimental:
        - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
        exclude:
        - { experimental: false, robotology: { yarp: master } }

    steps:
    - name: Check out main project
      uses: actions/checkout@v4

    - name: Check out YCM
      uses: actions/checkout@v4
      with:
        repository: robotology/ycm
        path: .deps/ycm

    - name: Check out YARP
      uses: actions/checkout@v4
      with:
        repository: robotology/yarp
        ref: ${{matrix.robotology.yarp}}
        path: .deps/yarp

    - name: Check out RapidJSON
      uses: actions/checkout@v4
      with:
        repository: Tencent/rapidjson
        path: .deps/rapidjson

    - name: Check out OpenRAVE
      uses: actions/checkout@v4
      with:
        repository: rdiankov/openrave
        path: .deps/openrave

    - name: Check out SWIG
      if: ${{matrix.system.os == 'ubuntu-24.04'}}
      uses: actions/checkout@v4
      with:
        repository: swig/swig
        ref: v4.2.1
        path: .deps/swig

    - name: Check out asrob-uc3m/yarp-devices
      uses: actions/checkout@v4
      with:
        repository: asrob-uc3m/yarp-devices
        path: .deps/yarp-devices

    - name: Check out roboticslab-uc3m/vision
      uses: actions/checkout@v4
      with:
        repository: roboticslab-uc3m/vision
        path: .deps/vision

    - name: Check out roboticslab-uc3m/kinematics-dynamics
      uses: actions/checkout@v4
      with:
        repository: roboticslab-uc3m/kinematics-dynamics
        path: .deps/kinematics-dynamics

    - name: Install dependencies via apt
      run: sudo apt-get update && sudo apt-get install -qq ccache libboost-regex-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libxml2-dev libpcl-dev

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{matrix.robotology.cmake}}

    - name: Set up Ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{matrix.system.os}}-${{matrix.robotology.yarp}}-${{matrix.system.compiler.cc}}

    - name: Set environment variables
      run: |
        echo "CC=${{matrix.system.compiler.cc}}" >> $GITHUB_ENV
        echo "CXX=${{matrix.system.compiler.cxx}}" >> $GITHUB_ENV

    - name: Build YCM
      run: |
        cmake -S .deps/ycm -B .deps/ycm/build
        cmake --build .deps/ycm/build
        sudo cmake --install .deps/ycm/build

    - name: Build YARP
      run: |
        cmake -S .deps/yarp -B .deps/yarp/build -DSKIP_ACE=ON -DYARP_DISABLE_VERSION_SOURCE=ON
        cmake --build .deps/yarp/build
        sudo cmake --install .deps/yarp/build

    - name: Build RapidJSON
      run: |
        cmake -S .deps/rapidjson -B .deps/rapidjson/build -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF -DRAPIDJSON_BUILD_TESTS=OFF
        cmake --build .deps/rapidjson/build
        sudo cmake --install .deps/rapidjson/build

    - name: Build OpenRAVE
      run: |
        CFLAGS=-w CXXFLAGS=-w cmake -S .deps/openrave -B .deps/openrave/build -DOPT_VIDEORECORDING=OFF -DOPT_PLUGINS=OFF -DOPT_PYTHON=OFF -DOPT_PYTHON3=OFF -DOPT_COLLADA=OFF -DOPT_CBINDINGS=OFF -DOPT_MSGPACK=OFF -DOPT_ENCRYPTION=OFF
        cmake --build .deps/openrave/build
        sudo cmake --install .deps/openrave/build

    - name: Build SWIG
      if: ${{matrix.system.os == 'ubuntu-24.04'}}
      run: |
        cmake -S .deps/swig -B .deps/swig/build
        cmake --build .deps/swig/build
        sudo cmake --install .deps/swig/build
        sudo ln -s /usr/local/bin/swig /usr/local/bin/swig4.0 # shadows /usr/bin/swig4.0

    - name: Build asrob-uc3m/yarp-devices
      run: |
        cmake -S .deps/yarp-devices -B .deps/yarp-devices/build
        cmake --build .deps/yarp-devices/build
        sudo cmake --install .deps/yarp-devices/build

    - name: Build roboticslab-uc3m/vision
      run: |
        cmake -S .deps/vision -B .deps/vision/build -DDOWNLOAD_MODELS=OFF
        cmake --build .deps/vision/build
        sudo cmake --install .deps/vision/build

    - name: Build roboticslab-uc3m/kinematics-dynamics
      run: |
        cmake -S .deps/kinematics-dynamics -B .deps/kinematics-dynamics/build
        cmake --build .deps/kinematics-dynamics/build
        sudo cmake --install .deps/kinematics-dynamics/build

    - name: Configure main project
      run: cmake -S . -B build -DCREATE_BINDINGS_PYTHON=ON -DENABLE_examples=ON

    - name: Compile main project
      run: cmake --build build

    - name: Install main project
      run: sudo cmake --install build && sudo ldconfig

    - name: Uninstall main project
      run: sudo cmake --build build --target uninstall
